"""Broker backend protocol for MT5-compatible execution."""

from __future__ import annotations

from typing import Protocol

from ..models.mt5 import Mt5AccountInfo, Mt5OrderResult, Mt5SymbolInfo, Mt5Tick
from ..models.orders import OrderRecord


class Mt5Backend(Protocol):
    def account_info(self, user_id: str, account_id: str) -> Mt5AccountInfo: ...

    def symbol_info(self, user_id: str, account_id: str, symbol: str) -> Mt5SymbolInfo: ...

    def symbol_tick(self, user_id: str, account_id: str, symbol: str) -> Mt5Tick: ...

    def place_order(self, order: OrderRecord) -> Mt5OrderResult: ...

    def modify_order(self, order: OrderRecord) -> Mt5OrderResult: ...

    def cancel_order(self, order: OrderRecord) -> Mt5OrderResult: ...

    def close_position(self, order: OrderRecord) -> Mt5OrderResult: ...

    def orders(self, user_id: str, account_id: str) -> list[dict]: ...

    def positions(self, user_id: str, account_id: str) -> list[dict]: ...
